### ISSUE TITLE
ToDo for v2.0.0

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/jhipster-core#178]
ToDo:
  - [x] `JHipsterBinaryOptions`
    - [x] remove `BINARY_OPTIONS`
    - [x] remove `BINARY_OPTION_VALUES`
  - [x] `JHipsterUnaryOptions`
    - [x] remove `UNARY_OPTIONS`
    - [x] replace `module.exports` by ` module.exports = Options; `
  - [x] `JHipsterFieldTypes`
    - [x] remove `COMMON_DB_TYPES`
    - [x] remove `CASSANDRA_TYPES`
  - [x] `JHipsterDatabaseTypes`
    - [x] remove the lowercase keys (`sql`, `couchbase`, etc.)
    - [x] replace `module.exports` by ` module.exports = Types; `
  - [x] `JHipsterRelationshipTypes`
    - [x] replace `module.exports` by `module.exports = RelationshipTypes`
  - [x] `JHipsterValidations`
    - [x] replace `module.exports` by `module.exports = Validations;`
  - [x] remove `DocumentParser::parse` (formerly `JDLParser::parse`)
  - [x] remove `JHipsterEntityExporter::exportToJSON`
  - [x] clean up exposed API
  - [x] update the doc
    - [x] write about the JDL application generation
  - [ ] write a PR in the generator to make the subgens work with v2
  - [ ] write a PR for JDL Studio
  - [ ] Bonus points: write a PR to make the "JDL samples" project great again

**Comment by deepu105** [comment]
@MathieuAA sorry if its a naive question, as I still didnt find the time to llok at the new code. The items being removed, are they being replaced? if not how are we handling the use cases?

**Comment by MathieuAA** [comment]
It's all being renamed. The release note being a draft, I don't think you can see itLe 3 févr. 2018 14:42, Deepu K Sasidharan <notifications@github.com> a écrit :@MathieuAA sorry if its a naive question, as I still didnt find the time to llok at the new code. The items being removed, are they being replaced? if not how are we handling the use cases?

**Comment by MathieuAA** [comment]
@deepu105 the code replacing the old one is already in the master branch. I've made easier accessing the JHipster constants. For the deprecated methods, I'll release a patch release with the deprecation warnings so that users can change. I'll make a PR for the generator before releasing to switch to the new code, to make the transition happen smoothly.

**Comment by gmarziou** [comment]
Sorry if I'm off context here but I have just converted to JDL lately :)

Currently, when there's a parsing error in import-jdl, the error is raised using 3 lines which works well for humans but does not seem like ideal for tools. With this work and new parser, is this something that will get covered?

**Comment by MathieuAA** [comment]
@gmarziou Can you elaborate with examples? I'm not sure I get what you mean. Do you mean [here](https://github.com/jhipster/jhipster-core/blob/master/lib/reader/jdl_reader.js#L42...L44)?

**Comment by gmarziou** [comment]
You understood correctly that I did not understand how these lines were generated 😆 Thanks for showing metheser lines of code, everything is fine for tooling.

**Comment by MathieuAA** [comment]
@gmarziou ;)

**Comment by bd82** [comment]
I Saw the new tag. 👍 
https://github.com/jhipster/jhipster-core/releases/tag/v2.0.0

Is the missing docs link in "whats new" because the docs are not ready yet
or an oopsy? 😄

**Comment by MathieuAA** [comment]
There's a PR, just wait 'til JHipster V5 is released.

**Comment by MathieuAA** [comment]
Closing this, as this is way past v2 and some tasks are out of scope right now.
