### ISSUE TITLE
TODO List for Chevrotain migration

### ISSUE THREAD

**Issue by bd82** [jhipster/jhipster-core#190]
- [x] - In Depth Review by @MathieuAA
- [x] - Additional tests to increase code coverage (100% ?) on DSL folder.
- [x] - Resolve [transformation](https://github.com/jhipster/jhipster-core/blob/da705bbb5a3445ccd6e586f0eb09460472db221d/lib/reader/jdl_reader.js#L44) of input messing up error messages locations.
- [x] - Reflective runtime validations to reduce TCO:
  - [x] - Validation of Application configuration key names in validator.js
  - [x] - Validate all defined tokens are actual used in by the parser.
- [x] - Define labels for the syntax diagram to be more readable. 
- [x] - Evaluate need for special web bundling handling.
- [x] - Resolve all the TODOs left
- [x] - Remove Old pegjs Parser.

**Comment by bd82** [comment]
I will add more issues as I find them.

**Comment by MathieuAA** [comment]
Here's my roadmap for this week-end:
  - finish v2
  - write the doc
  - make a PR in the generator for the subgens

I'll review the branch by creating issues with a special label for this branch.
Everything I don't understand will go in an issue (one by question/problem).

**Comment by bd82** [comment]
Great. I am fixing a (general) performance bottleneck discovered thanks to this re-write 👍 
and will get back to the polishing work afterwards (soon).

**Comment by bd82** [comment]
I will improve code coverage here and there during this week but not many unblocked items to do...

- For running tests on many samples we still need to get the samples (@jdubois said after JHipster 5)
  * But with high coverage and how easy it was to fix the few incompatibilities found I'm less worried about those tbh.

- For [Bundling concerns](http://sap.github.io/chevrotain/website/FAQ.html#WEBPACK) I need your feedback @MathieuAA.
  * Does anybody bundle jhipster-core package for web use?
  * If so is it their responsibility to use the correct bundling & minification options or should
     jhipster-core include a bundled & minified version in its release?

**Comment by bd82** [comment]
Hello @MathieuAA 

I have a bit of time now between larger projects.
I see the master branch has advanced a bit.

Should I try to rebase the migration branch on top of the master branch and apply the grammar changes that have diverged ?

**Comment by MathieuAA** [comment]
I believe it's safe to do so. I've mainly fixed the app gen and am working on polishing some things.

**Comment by MathieuAA** [comment]
@bd82 I think we can close this one next week, as soon as I check the tests and remove pegjs from this project.

**Comment by MathieuAA** [comment]
I'm wondering, is the file `generated_serialized_grammar.js` used elsewhere? I'd like to remove it as it doesn't add any information already present elsewhere.

**Comment by bd82** [comment]
It was used in conjunction with https://rawgit.com/ to demonstrate the syntax diagrams.
You can ignore it and remove it from source control and only inspect the syntax diagrams
"locally"

**Comment by bd82** [comment]
Additional tests here:
https://github.com/jhipster/jhipster-core/pull/231

**Comment by bd82** [comment]
Once #240 is merged I think I don't have more leftover tasks in this context.

**Comment by MathieuAA** [comment]
@bd82 I've changed my mind, let's keep the serialized grammar... the HTML version could be helpful for anyone wishing to have a look at the grammar.

**Comment by bd82** [comment]
@MathieuAA Do you want to share the **development** version of the diagrams or only official **release** versions?

Because we can put this serialized file in the npm package and render the **release** diagrams from unpkg.com (npm cdn) but avoid polluting the source control history.

**Comment by MathieuAA** [comment]
Having the latest grammar is enough for most use cases. I only kept it for the documentation

**Comment by bd82** [comment]
> Having the latest grammar is enough for most use cases. I only kept it for the documentation

o.k.

If we write the grammar and lexer files as **UMD** models (in the source code).
We can load the diagrams **without** a serialization step.
Something like this: https://github.com/SAP/chevrotain/blob/master/examples/parser/diagrams/grammar.js#L3-L13

**Comment by bd82** [comment]
Is there anything else here that requires my assistance?

**Comment by bd82** [comment]
Great 😄

**Comment by MathieuAA** [comment]
It's finally done! Again, huge thanks @bd82 :)

**Comment by bd82** [comment]
Now lets see what 🐛 🐞  we have not swatted yet 😄
